# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# jet. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that jet is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.


# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.
DEVICE_PACKAGE_OVERLAYS := device/samsung/jet/overlay

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES := \
    device/samsung/jet/egl.cfg:system/lib/egl/egl.cfg \
    device/samsung/jet/vold.fstab:system/etc/vold.fstab \
    device/common/gps/gps.conf_EU_SUPL:system/etc/gps.conf \
    device/samsung/jet/media_profiles.xml:system/etc/media_profiles.xml

# Init files
PRODUCT_COPY_FILES += \
    device/samsung/jet/init.rc:root/init.rc \
    device/samsung/jet/init.jet.rc:root/init.jet.rc \
    device/samsung/jet/ueventd.jet.rc:root/ueventd.jet.rc \
    device/samsung/jet/recovery.rc:root/recovery.rc

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
    device/samsung/jet/samsung-keypad.kl:system/usr/keylayout/samsung-keypad.kl \
    device/samsung/jet/sec_jack.kl:system/usr/keylayout/sec_jack.kl \
    device/samsung/jet/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl

# Generated kcm keymaps
PRODUCT_PACKAGES := \
    samsung-keypad.kcm \
    gpio-keys.kcm

# Input device calibration files
PRODUCT_COPY_FILES += \
    device/samsung/jet/qt5480_ts_input.idc:system/usr/idc/qt5480_ts_input.idc

# Libs
PRODUCT_PACKAGES += \
    lights.jet \
    gps.jet \
    libs3cjpeg \
    libcamera \
    bdaddr_read \
    show_logo \
    copybit.s3c6410 \
    gralloc.s3c6410 \
    libsecgps.so \
    libsec-ril.so \
    libsecril-client.so \
    efsd \
    libGLES_fimg

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
    frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
    frameworks/base/data/etc/android.hardware.camera.autofocus.xml:system/etc/permissions/android.hardware.camera.autofocus.xml \
    frameworks/base/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
    frameworks/base/data/etc/android.hardware.location.xml:system/etc/permissions/android.hardware.location.xml \
    frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
    frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
    frameworks/base/data/etc/android.hardware.touchscreen.multitouch.distinct.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
    frameworks/base/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
    packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# Sensors
PRODUCT_COPY_FILES += \
    device/samsung/jet/prebuilt/akmd/akmd:system/bin/akmd

# Wifi
PRODUCT_COPY_FILES += \
    device/samsung/jet/prebuilt/wifi/nvram.txt:system/etc/nvram.txt \
    device/samsung/jet/prebuilt/wifi/fw_bcm4325.bin:system/etc/fw_bcm4325.bin \
    device/samsung/jet/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf

# serviceModeApp
PRODUCT_COPY_FILES += \
    device/samsung/jet/prebuilt/servicemodeapp/serviceModeApp.apk:system/app/serviceModeApp.apk

# Bluetooth
PRODUCT_COPY_FILES += \
    device/samsung/jet/prebuilt/bt/bcm4325.hcd:system/etc/bcm4325.hcd

# Boot logo
PRODUCT_COPY_FILES += \
    device/samsung/jet/bootlogo.png:system/etc/bootlogo.png

# Used by BusyBox
KERNEL_MODULES_DIR:=/lib/modules

# Enable Windows Media if supported by the board
WITH_WINDOWS_MEDIA:=true

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
    ro.opengles.version=65537

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
       wifi.interface=wlan0 \
       wifi.supplicant_scan_interval=20 \
       ro.telephony.ril_class=jet \
       mobiledata.interfaces=pdp0,wlan0,gprs,ppp0 \
       dalvik.vm.heapsize=32m \
       dalvik.vm.dexopt-data-only=1 \

# enable Google-specific location features,
# like NetworkLocationProvider and LocationCollector
PRODUCT_PROPERTY_OVERRIDES += \
        ro.com.google.locationfeatures=1 \
        ro.com.google.networklocation=1

# Extended JNI checks
# The extended JNI checks will cause the system to run more slowly, but they can spot a variety of nasty bugs 
# before they have a chance to cause problems.
# Default=true for development builds, set by android buildsystem.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.kernel.android.checkjni=0 \
    dalvik.vm.checkjni=false

# Screen density is actually considered a locale (since it is taken into account
# the the build-time selection of resources). The product definitions including
# this file must pay attention to the fact that the first entry in the final
# PRODUCT_LOCALES expansion must not be a density.
PRODUCT_LOCALES := mdpi

# Kernel
LOCAL_KERNEL := device/samsung/jet/kernel.bin
PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/samsung/jet/jet-vendor.mk)
